;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="State.Movement.Run",NewTagName="State.Movement.Runing")
+GameplayTagRedirects=(OldTagName="State.Movement.Walk",NewTagName="State.Movement.Walking")
+GameplayTagRedirects=(OldTagName="State.Movement.Failing",NewTagName="State.Movement.Falling")
+GameplayTagRedirects=(OldTagName="State",NewTagName="Abilities")
+GameplayTagRedirects=(OldTagName="Event.Item.Equip.Complete",NewTagName="Event.Item.Equip.Completed")
+GameplayTagRedirects=(OldTagName="Abilities.Combat.Weapon.Melee",NewTagName="Abilities.Combat.Weapon.Melee")
+GameplayTagRedirects=(OldTagName="Event.Ride.Skills",NewTagName="Event.Ride.EndSkill")
+GameplayTagList=(Tag="Abilities.Combat.Block",DevComment="")
+GameplayTagList=(Tag="Abilities.Combat.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Abilities.Combat.LightAttack",DevComment="")
+GameplayTagList=(Tag="Abilities.Combat.Parry",DevComment="")
+GameplayTagList=(Tag="Abilities.Combat.Slip",DevComment="")
+GameplayTagList=(Tag="Abilities.Cover.ExitCover",DevComment="")
+GameplayTagList=(Tag="Abilities.Cover.TakeCover",DevComment="")
+GameplayTagList=(Tag="Abilities.HitReaction",DevComment="")
+GameplayTagList=(Tag="Abilities.Item.Equip",DevComment="")
+GameplayTagList=(Tag="Abilities.Item.Interact",DevComment="")
+GameplayTagList=(Tag="Abilities.Item.Unequip",DevComment="")
+GameplayTagList=(Tag="Abilities.Movement.Jump",DevComment="")
+GameplayTagList=(Tag="Abilities.Movement.Traverse",DevComment="")
+GameplayTagList=(Tag="Abilities.Ragdoll",DevComment="")
+GameplayTagList=(Tag="Abilities.Ride.SharpBrake",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Instant",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Attack",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Attack.TraceEnd",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Block",DevComment="")
+GameplayTagList=(Tag="Event.Combat.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Event.Combat.LightAttack",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Parry",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Weapon.Explode",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Weapon.Throw",DevComment="")
+GameplayTagList=(Tag="Event.Cover.ExitCover",DevComment="")
+GameplayTagList=(Tag="Event.Cover.TakeCover",DevComment="")
+GameplayTagList=(Tag="Event.HitReaction",DevComment="")
+GameplayTagList=(Tag="Event.Interact",DevComment="")
+GameplayTagList=(Tag="Event.Item.Equip",DevComment="")
+GameplayTagList=(Tag="Event.Item.Equip.Completed",DevComment="")
+GameplayTagList=(Tag="Event.Item.Unequip.Completed",DevComment="")
+GameplayTagList=(Tag="Event.PlayMontage",DevComment="")
+GameplayTagList=(Tag="Event.Ragdoll",DevComment="")
+GameplayTagList=(Tag="Event.Ragdoll.Enable",DevComment="")
+GameplayTagList=(Tag="Event.Ride.BrakeEnd",DevComment="")
+GameplayTagList=(Tag="Event.Ride.EndSkill",DevComment="")
+GameplayTagList=(Tag="Event.Ride.Jump",DevComment="")
+GameplayTagList=(Tag="Gameplay.Camera.Changed",DevComment="")
+GameplayTagList=(Tag="Gameplay.Camera.FirstPerson",DevComment="")
+GameplayTagList=(Tag="Gameplay.Camera.OverShoulder",DevComment="")
+GameplayTagList=(Tag="Gameplay.Camera.ThirdPerson",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.LightAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Shoot",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Explode",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Projectile.Hit",DevComment="")
+GameplayTagList=(Tag="StateTree.Event.Attack",DevComment="")
+GameplayTagList=(Tag="StateTree.Event.GotTarget",DevComment="")
+GameplayTagList=(Tag="Status.Attack.HasAttackToken",DevComment="")
+GameplayTagList=(Tag="Status.Attack.IsUnderAttack.Fire",DevComment="")
+GameplayTagList=(Tag="Status.Attack.IsUnderAttack.Melee",DevComment="")
+GameplayTagList=(Tag="Status.Attack.IsUnderAttack.Throw",DevComment="")
+GameplayTagList=(Tag="Status.IsDead",DevComment="")
+GameplayTagList=(Tag="Status.Weapon.HasWeapon",DevComment="")
+GameplayTagList=(Tag="Status.Weapon.HasWeapon.Explosive",DevComment="")
+GameplayTagList=(Tag="Status.Weapon.HasWeapon.Melee",DevComment="")
+GameplayTagList=(Tag="Status.Weapon.HasWeapon.Ranged",DevComment="")
+GameplayTagList=(Tag="Status.Weapon.LowAmmo",DevComment="")
+GameplayTagList=(Tag="Tests.Health",DevComment="")
+GameplayTagList=(Tag="Tests.Health.High",DevComment="")
+GameplayTagList=(Tag="Tests.Health.Low",DevComment="")
+GameplayTagList=(Tag="Utility.InterruptTask",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Combat",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Combat.Attack",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Combat.Attack.Fire",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Combat.Attack.Hand",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Combat.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Combat.Attack.Throw",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Combat.Flank",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Combat.Parry",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Combat.Tactical.ChaseTarget",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Flee",DevComment="")
+GameplayTagList=(Tag="Utility.Task.Idle",DevComment="")
+GameplayTagList=(Tag="Utility.Task.MoveTo",DevComment="")

